JComm_x64:
	g++ -I"%JAVA_HOME%\include" -I"%JAVA_HOME%\include\win32" --share com_ray_JComm.cpp -o JComm.dll -m6
4
JComm_x86:
	g++ -I"%JAVA_HOME%\include" -I"%JAVA_HOME%\include\win32" --share com_ray_JComm.cpp -o JComm.dll -m32