JComm64:
	g++ -I"%JAVA_HOME%\include" -I"%JAVA_HOME%\include\win32" --share com_ray_JComm.cpp -o JComm.dll -m64
JComm32:
	g++ -I"%JAVA_HOME%\include" -I"%JAVA_HOME%\include\win32" --share com_ray_JComm.cpp -o JComm.dll -m32